(() => {
  const root=document.body.dataset.root||'../';
  const list=document.querySelector('[data-busy-list]');
  if(list){list.innerHTML=BUSY_WORK_ACTIVITIES.map(a=>`<article class="busy-card"><p class="module-area">${typeof a.module==='number'?`Module ${a.module}`:a.module} · about 20 minutes</p><h2>${a.title}</h2><p>${a.focus}</p><p class="fine"><strong>Mechanic:</strong> ${a.mechanic}</p><a class="button" href="activity-${String(a.id).padStart(2,'0')}.html">Open activity</a></article>`).join('');return;}
  const id=Number(document.body.dataset.activityId),a=BUSY_WORK_ACTIVITIES.find(item=>item.id===id);if(!a)return;
  document.title=`${a.title} | Year 11 Textiles and Design`;
  const moduleLink=typeof a.module==='number'?`<a href="${root}modules/module-${String(a.module).padStart(2,'0')}.html">Return to Module ${a.module}</a>`:`<a href="${root}index.html#modules">Review the course modules</a>`;
  document.querySelector('#main').innerHTML=`<section class="page-hero"><div class="wrap"><p class="eyebrow">${typeof a.module==='number'?`Module ${a.module}`:a.module} · ${a.mechanic} · about 20 minutes</p><h1>${a.title}</h1><p class="lede">${a.focus}</p></div></section><section><div class="wrap activity-layout"><div><article class="activity-card"><p class="eyebrow">Work sequence</p><h2>Build usable evidence</h2><ol><li>Answer from course knowledge first.</li><li>Check the relevant module and revise in a different colour.</li><li>Use specific textile evidence and explain the connection.</li></ol><div class="evidence-checklist"><strong>Authority boundary</strong><p>Use only teacher-approved practical procedures. Current formal task notices control assessment conditions.</p></div></article><form>${a.fields.map((label,index)=>`<article class="activity-card"><p class="module-area">Stage ${index+1}</p><label for="field-${index}"><strong>${label}</strong></label><textarea id="field-${index}" data-busy-field="${index}" rows="6"></textarea><p class="save-status" aria-live="polite"></p></article>`).join('')}<article class="activity-card"><h2>Finish and carry evidence forward</h2><p>Review for accurate terms, relevant evidence and an explicit link to the question.</p><div class="button-row screen-only"><button class="button" type="button" data-busy-print>Print activity</button><a class="button secondary" href="index.html">Choose another activity</a></div></article></form></div><aside class="module-aside"><article class="panel"><p class="eyebrow">Progress</p><div class="progress-track"><div class="progress-fill" data-busy-progress></div></div><p class="fine" data-busy-progress-text></p></article><article class="panel"><p class="eyebrow">Course connection</p><p>${moduleLink}</p><p><a href="${root}folio.html">Open My folio</a></p></article><article class="panel"><p class="eyebrow">Privacy</p><p class="fine">Responses save only in this browser on this device. Use print to keep a portable copy.</p></article></aside></div></section>`;
  const fields=[...document.querySelectorAll('[data-busy-field]')],key=i=>`${TEXTILES_STORAGE_PREFIX}:busy:${String(id).padStart(2,'0')}:${i}`;
  const update=()=>{const started=fields.filter(f=>f.value.trim().length>=20).length,pct=Math.round(started/fields.length*100);document.querySelector('[data-busy-progress]').style.width=`${pct}%`;document.querySelector('[data-busy-progress-text]').textContent=`${started} of ${fields.length} evidence stages started`;};
  fields.forEach((field,index)=>{field.value=localStorage.getItem(key(index))||'';let timer;field.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(key(index),field.value);const status=field.closest('.activity-card').querySelector('.save-status');status.textContent='Saved on this device';setTimeout(()=>status.textContent='',1200);update();},180);});});
  document.querySelector('[data-busy-print]').addEventListener('click',()=>window.print());update();
})();
