const TEXTILES_MODULE_VIDEOS = [
  {module:2,id:'yDZitOgh47I',title:'From Ideation to Printed Fabric | My 6 Step Process',creator:'Mel Armstrong - Illustrator',watchFor:'Track how an initial idea is researched, developed, tested and refined before it becomes a textile design.',relevance:'Supports design development and purposeful refinement; the course theory remains the authority for focus areas and design factors.'},
  {module:3,id:'2I0iDN6p-Q4',title:'How to read a Sewing Pattern for Beginners',creator:'Tock Custom',watchFor:'Pause on the envelope, pattern pieces and common symbols. Match each marking to the information it communicates.',relevance:'Supports commercial-pattern interpretation. Students must still follow the teacher-issued pattern, instructions and local safety controls.'},
  {module:4,id:'ORjlEpjiHrU',title:'Behind the Scenes: A day in the life of a Textile Designer',creator:'The Careers Department',watchFor:'Notice the different visual, written and digital ways the designer communicates ideas to other people.',relevance:'Provides a real communication context without prescribing the class project.'},
  {module:5,id:'E5jH5T63I2s',title:'The Complete Fashion Design to Production Process',creator:'FittDesign Studio',watchFor:'Identify where planning, refinement, quality checks and evaluation appear across the development process.',relevance:'Provides a broad production context; students use their teacher’s current project brief and requirements.'},
  {module:6,id:'PDuiSnBYCQc',title:'Fibres to Fabrics — Introduction and types of fibres',creator:'Sri Chaitanya Academy NEET',watchFor:'Follow the hierarchy from fibre to yarn to fabric and note the broad natural and manufactured classifications.',relevance:'A concise orientation beside the course’s more detailed fibre classification and structure theory.'},
  {module:7,id:'hNC1fK6GjF4',title:'Classification of Textile Fibres',creator:'Textile Vlog',watchFor:'Sort the examples by origin and production, then compare that classification with the natural, regenerated and synthetic groups in the module.',relevance:'Reinforces classification; fibre properties and lifecycle judgements must still use the course evidence.'},
  {module:8,id:'bNHAKZ6bNEk',title:'Yarn manufacture from staple fibres: twist and its effect',creator:'Vidya-mitra',watchFor:'Notice how fibres are aligned and twisted, and how changing twist alters the yarn rather than simply changing its appearance.',relevance:'Supports staple-spun yarn formation and twist relationships.'},
  {module:9,id:'Ow5W7boAaTs',title:'Textile Yarns — Twisting and Plying',creator:'Textile with Alberto',watchFor:'Identify single and plied structures, then predict how construction may change strength, balance and handle.',relevance:'Supports structure–property reasoning and end-use justification.'},
  {module:10,id:'TYrQBcPBk3U',title:'The 3 Fundamental Textile Weaves: Plain, Twill and Satin',creator:'Textile with Alberto',watchFor:'Compare the interlacement repeat in plain, twill and satin rather than relying only on surface appearance.',relevance:'Directly supports the woven-structure section; knitted and non-woven structures remain in the adjacent course theory.'},
  {module:11,id:'QssaPcq2v7M',title:"FIT's Textile-Testing Lab",creator:'Fashion Institute of Technology',watchFor:'Look for controlled conditions, repeatable measurement and the connection between a test result and a product decision.',relevance:'Shows professional testing context without setting the school’s apparatus, method or WHS controls.'},
  {module:12,id:'4W-TxcRMEyk',title:'Testing of textile fabrics: objectives',creator:'Vidya-mitra',watchFor:'Identify why a property is tested and how results can support selection, comparison and quality decisions.',relevance:'Supports using experimental evidence in Project 2 while the teacher-approved practical method remains authoritative.'},
  {module:13,id:'C3acJpAJw-E',title:'Textile: From Fibers to Fashion | Industry Supply Chain Explained',creator:'suppliersplatform',watchFor:'Map the stages from materials through manufacture and distribution, then identify how one change can affect several stages.',relevance:'A broad value-chain view used alongside current Australian industry and training sources.'},
  {module:14,id:'joBUUSa-cfc',title:'Behind the Seams: Ensuring Quality at Every Step from Design to Delivery',creator:'Hold-True',watchFor:'Separate actions that prevent defects from checks that detect defects, and note where evidence is recorded.',relevance:'Supports quality assurance and control; it is an industry example rather than a required class process.'},
  {module:15,id:'Lbuo0i1F1yA',title:'Mastering Exam Command Terms',creator:'School of Learning',watchFor:'Listen for how command words change the depth and structure of a response, then compare the advice with this module’s exact definitions.',relevance:'Supports response planning. The course theory and the teacher’s issued assessment notice remain authoritative.'}
];

for (const item of TEXTILES_MODULE_VIDEOS) {
  const module = COURSE_MODULES.find(entry => entry.id === item.module);
  if (!module || !module.sections?.length) continue;
  module.sections[0].video = {...item, duration:'Short learning clip', published:'See YouTube'};
}
