(() => {
  const id=Number(document.body.dataset.module),data=COURSE_MODULES.find(module=>module.id===id);
  if(!data)return;
  const pad=value=>String(value).padStart(2,'0');
  const header=document.querySelector('[data-module-hero]');
  document.title=`Module ${id}: ${data.title} | Year 11 Textiles and Design`;
  header.innerHTML=`<p class="eyebrow">Module ${id} of 15 · Weeks ${data.weeks} · ${data.area}</p><h1>${data.title}</h1><p class="lede">${data.summary}</p>`;
  const main=document.querySelector('[data-module-main]');
  const aside=document.querySelector('[data-module-aside]');

  if(!data.complete){
    main.innerHTML=`${renderOverview(false)}${renderEvidence(false)}<section class="resource-gap-note"><p class="eyebrow">Mapped, not yet a complete lesson</p><h2>The learning route is ready; the teaching package is not.</h2><p>This module still needs source-approved explanation, purposeful visuals, a student presentation, section-matched videos, guided checks and saved written responses. Use the headings to see where the course is going, but do not treat this preview as finished learning material.</p></section><section class="preview-sections" aria-label="Planned module sections">${data.sections.map((title,index)=>`<article class="preview-card"><p class="module-area">Section ${id}.${index+1}</p><h3>${title}</h3><p>You will explain this idea and connect it to a relevant textile example, material, process or design decision.</p><p class="evidence-marker"><strong>Evidence to keep:</strong> a supported explanation, annotated example or justified choice will be added when this section is fully authored.</p></article>`).join('')}</section>${renderCompletion(false)}`;
    aside.innerHTML=`<article class="panel"><p class="eyebrow">In this module</p><ol class="section-nav">${data.sections.map(title=>`<li>${title}</li>`).join('')}</ol></article><article class="panel"><p class="eyebrow">Source boundary</p><strong>Teacher-directed learning</strong><p class="fine">Use current teacher-approved project, practical and assessment instructions alongside this course theory.</p></article>`;
    setPagination();
    return;
  }

  main.innerHTML=`${renderOverview(true)}${renderEvidence(true)}${data.sections.map((section,index)=>renderSection(section,index)).join('')}${renderCompletion(true)}<nav class="module-pagination screen-only" aria-label="Module sequence"><a class="button secondary" data-previous></a><a class="button" data-next></a></nav>`;
  aside.innerHTML=`<article class="panel"><p class="eyebrow">In this module</p><ol class="section-nav">${data.sections.map((section,index)=>`<li><a href="#${section.id}">${index+1}. ${section.title}</a></li>`).join('')}</ol></article><article class="panel"><p class="eyebrow">Your progress</p><div class="progress-track"><div class="progress-fill" data-progress></div></div><p class="fine" data-progress-text></p><a href="../folio.html">Open My folio →</a></article><article class="panel"><p class="eyebrow">Apply the learning</p><h3>${data.activity.title}</h3><p>Use the module ideas in a purposeful practice activity and keep your evidence.</p><a class="button secondary compact" href="${data.activity.url}">Open activity</a></article><button type="button" class="button secondary screen-only" data-print>Print Module ${id}</button>`;
  bindInteractions();
  setPagination();
  updateProgress();

  function renderOverview(complete){
    const action=complete?`<div class="module-overview-action"><p class="eyebrow">Start here</p><p>Use the presentation before the theory sections. It previews the ideas and the response routine.</p><a class="button red" href="${data.presentation.url}" download>Download 8-slide PowerPoint</a><a class="button secondary" href="${data.presentation.previewUrl}">Open browser presentation</a></div>`:`<div class="module-overview-action"><p class="eyebrow">Current status</p><p>The module purpose and section sequence are mapped. Complete learning resources are still being prepared.</p><span class="button secondary" aria-disabled="true">Presentation source required</span></div>`;
    return `<section class="module-overview"><div><p class="eyebrow">Module overview</p><h2>${data.nextAction}</h2><p>${data.summary}</p><div class="module-meta"><span>Weeks ${data.weeks}</span><span>${data.area}</span><span>${data.sections.length} sections</span></div></div>${action}</section>`;
  }
  function renderEvidence(complete){
    const items=complete?['30 checked knowledge questions','3 saved written responses','1 applied-practice activity linked to My folio']:['Section explanations and examples','Guided knowledge checks','Saved written evidence linked to My folio'];
    return `<section class="student-evidence-strip"><div><p class="eyebrow">Student evidence</p><h2>${complete?'What you will keep':'What the finished module must produce'}</h2><p class="fine">${complete?'Your work saves on this device.':'These evidence tools are planned but not yet active on this route.'}</p></div><ul class="evidence-list">${items.map(item=>`<li>${item}</li>`).join('')}</ul></section>`;
  }
  function renderCompletion(complete){
    if(!complete)return `<section class="completion-card"><p class="eyebrow">Module boundary</p><h2>Continue through the mapped course</h2><p>This page confirms the place and purpose of Module ${id}. Completion can only be added after the required student learning and evidence resources are built and checked.</p></section>`;
    return `<section class="completion-card"><p class="eyebrow">Complete Module ${id}</p><h2>Check, save and carry your evidence forward</h2><p data-progress-text></p><p>Before moving on, correct the knowledge checks, save all three written responses and complete the applied-practice activity. Open My folio to review the evidence held on this device.</p><div class="completion-actions screen-only"><a class="button" href="${data.activity.url}">Complete Module ${id} activity</a><a class="button secondary" href="../folio.html">Review My folio</a><button type="button" class="button secondary" data-completion-print>Print module</button></div></section>`;
  }

  function renderSection(section,index){
    const visualMarkup=section.mobileVisual?`<picture><source media="(max-width: 680px)" srcset="${section.mobileVisual}"><img src="${section.visual}" alt="${section.visualAlt}"></picture>`:`<img src="${section.visual}" alt="${section.visualAlt}">`;
    const videoMarkup=section.video?`<aside class="video-learning"><div><p class="eyebrow">Watch and notice</p><h3>${section.video.title}</h3><p>${section.video.watchFor}</p><p class="fine">${section.video.creator} · ${section.video.duration||'Short learning clip'} · link rechecked ${TEXTILES_VIDEO_MANIFEST.checked}</p><p><a href="https://www.youtube.com/watch?v=${section.video.id}" target="_blank" rel="noopener">Open in YouTube ↗</a> · <a href="../video-learning/index.html#${section.id}">Open in Video learning</a></p></div><div class="video-frame" data-video-frame><button class="video-launch" type="button" data-video-load="${section.video.id}" data-video-title="${section.video.title}" aria-label="Play ${section.video.title}"><img src="https://i.ytimg.com/vi/${section.video.id}/hqdefault.jpg" alt="Thumbnail for ${section.video.title}" loading="lazy"><span class="video-play" aria-hidden="true">▶</span></button></div></aside>`:`<aside class="video-learning video-learning-link"><div><p class="eyebrow">Extend the section</p><h3>Video learning library</h3><p>Use the validated module clip after reading this section, then return here to complete the checks.</p><p><a href="../video-learning/index.html#module-${id}">Open Module ${id} video learning →</a></p></div></aside>`;
    return `<section class="theory-section" id="${section.id}"><p class="module-area">Section ${id}.${index+1}</p><h2>${section.title}</h2>${section.theory}<figure class="teaching-visual"><div class="visual-frame"><a href="${section.visual}" target="_blank" rel="noopener">${visualMarkup}</a></div><figcaption>${section.visualCaption}</figcaption><p class="visual-links"><a href="${section.visual}" target="_blank" rel="noopener">Open larger</a></p></figure>${videoMarkup}</section><details class="learning-cycle"><summary><span>Learning activity ${id}.${index+1}</span><strong>10 checks + one written response</strong></summary><div class="learning-body"><p>Use the section directly above. Check each answer, then build your written response.</p><div data-section-id="${section.id}">${section.questions.map((question,qIndex)=>renderQuestion(section,question,qIndex)).join('')}</div>${renderWritten(section,index)}</div></details>`;
  }
  function renderQuestion(section,item,index){
    const saved=readJSON(`${TEXTILES_STORAGE_PREFIX}:check:${section.id}:${index}`);
    return `<fieldset class="question" data-question="${index}"><legend>${index+1}. ${item.question}</legend>${item.options.map((option,optionIndex)=>`<label class="option"><input type="radio" name="${section.id}-q${index}" value="${optionIndex}"${saved.selected===optionIndex?' checked':''}> <span>${option}</span></label>`).join('')}<button class="button secondary compact" type="button" data-check>Check answer</button><p class="feedback ${saved.checked?(saved.correct?'good':'try'):''}" aria-live="polite">${saved.checked?(saved.correct?item.correctFeedback:item.retryFeedback):''}</p></fieldset>`;
  }
  function renderWritten(section,index){
    const w=section.written;
    return `<section class="written-response"><p class="eyebrow">Written evidence ${id}.${index+1}</p><h3>${w.prompt}</h3><p><strong>Read → Select → Explain → Check</strong></p><button class="button secondary compact" type="button" data-help aria-expanded="false" aria-controls="guide-${section.id}">What is this asking?</button><div class="response-guide" id="guide-${section.id}" hidden><p><strong>Return to theory:</strong> <a href="#${section.id}">${section.title}</a></p><p><strong>In plain language:</strong> ${w.clarify}</p><ol>${w.steps.map(step=>`<li>${step}</li>`).join('')}</ol><p><strong>Sentence starter:</strong> ${w.starter}</p><details><summary>Appropriate response example</summary><p>${w.example}</p></details></div><label class="sr-only" for="response-${section.id}">Response to ${w.prompt}</label><textarea id="response-${section.id}" data-save-key="${TEXTILES_STORAGE_PREFIX}:response:${section.id}" placeholder="Write your response here…"></textarea><p class="save-status" aria-live="polite"></p></section>`;
  }
  function bindInteractions(){
    TextilesVideoPlayer.bind();
    document.querySelectorAll('[data-check]').forEach(button=>button.addEventListener('click',()=>{const fieldset=button.closest('.question'),sectionId=button.closest('[data-section-id]').dataset.sectionId,section=data.sections.find(item=>item.id===sectionId),qIndex=Number(fieldset.dataset.question),selected=fieldset.querySelector('input:checked'),feedback=fieldset.querySelector('.feedback');if(!selected){feedback.className='feedback try';feedback.textContent='Choose an answer, then check again.';return}const selectedIndex=Number(selected.value),correct=selectedIndex===section.questions[qIndex].answer;localStorage.setItem(`${TEXTILES_STORAGE_PREFIX}:check:${section.id}:${qIndex}`,JSON.stringify({selected:selectedIndex,checked:true,correct}));feedback.className=`feedback ${correct?'good':'try'}`;feedback.textContent=correct?section.questions[qIndex].correctFeedback:section.questions[qIndex].retryFeedback;updateProgress()}));
    document.querySelectorAll('[data-help]').forEach(button=>button.addEventListener('click',()=>{const panel=document.getElementById(button.getAttribute('aria-controls')),open=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!open));panel.hidden=open}));
    document.querySelectorAll('[data-save-key]').forEach(area=>{area.value=localStorage.getItem(area.dataset.saveKey)||'';let timer;area.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(area.dataset.saveKey,area.value);area.nextElementSibling.textContent='Saved on this device';setTimeout(()=>area.nextElementSibling.textContent='',1400);updateProgress()},220)})});
    document.querySelector('[data-print]').addEventListener('click',()=>window.print());
    document.querySelector('[data-completion-print]').addEventListener('click',()=>window.print());
  }
  function updateProgress(){const correct=data.sections.reduce((total,section)=>total+section.questions.filter((_,index)=>readJSON(`${TEXTILES_STORAGE_PREFIX}:check:${section.id}:${index}`).correct).length,0),responses=data.sections.filter(section=>(localStorage.getItem(`${TEXTILES_STORAGE_PREFIX}:response:${section.id}`)||'').trim().length>=20).length,pct=Math.round(((correct+responses)/33)*100);document.querySelector('[data-progress]').style.width=`${pct}%`;document.querySelectorAll('[data-progress-text]').forEach(node=>node.textContent=`${correct} of 30 checks correct · ${responses} of 3 written responses saved`)}
  function readJSON(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch(_){return{}}}
  function setPagination(){const previous=document.querySelector('[data-previous]'),next=document.querySelector('[data-next]');if(!previous||!next){const nav=document.createElement('nav');nav.className='module-pagination screen-only';nav.setAttribute('aria-label','Module sequence');nav.innerHTML='<a class="button secondary" data-previous></a><a class="button" data-next></a>';main.append(nav)}const p=document.querySelector('[data-previous]'),n=document.querySelector('[data-next]');p.href=id===1?'../index.html':`module-${pad(id-1)}.html`;p.textContent=id===1?'← Course home':`← Module ${id-1}`;n.href=id===15?'../folio.html':`module-${pad(id+1)}.html`;n.textContent=id===15?'Open My folio →':`Module ${id+1} →`}
})();
